### ISSUE TITLE
Any stable evaluation metrics

### ISSUE THREAD

**Issue by ReinholdM** [THUDM/Android-Lab#2]
Hi! Thanks for the great work on OS-agent. I noticed the evaluation was done by llms automatically. And is there any task can be evaluated without llms, that is stable evaluation.

**Comment by xuyifan-0731** [comment]
In our dataset, the metrics for the 93 Operation Tasks are evaluated using stable evaluation metrics by directly assessing the corresponding positions in the UI tree. For the 45 Query Tasks, standard answers have been defined. However, to slightly relax the criteria for correct model responses, we opted to use an LLM for evaluation. If you wish to use stable evaluation metrics instead, you can directly modify the evaluation approach to calculate accuracy in a manner similar to fill-in-the-blank questions.
